### ISSUE TITLE
MidjourneyInteractionException when calling imagine

### ISSUE THREAD

**Issue by apoleo88** [hawkkiller/midjourney_client#48]
I get this error after calling .imagine, testing on window

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MidjourneyInteractionException: {"message": "Integrazione sconosciuta", "code": 10005}
#0      DiscordInteractionClientImpl._interactions (package:midjourney_client/src/discord/discord_interaction_client.dart:70:7)
<asynchronous suspension>
#1      RateLimiter.call (package:midjourney_client/src/utils/rate_limiter.dart:30:5)
<asynchronous suspension>
#2      DiscordInteractionClientImpl.imagine (package:midjourney_client/src/discord/discord_interaction_client.dart:126:5)
<asynchronous suspension>
#3      MidjourneyApiDiscordImpl.imagine (package:midjourney_client/src/midjourney/midjourney_api.dart:63:19)
<asynchronous suspension>

```

**Comment by cfatrane** [comment]
Hello, did you manage to resolve the problem?
